from __future__ import annotations

from pathlib import Path

from src.io_utils import ensure_dir


def render_watchlist_html(rows: list[dict], output_path: Path) -> Path:
    ensure_dir(output_path.parent)

    row_html = "\n".join(
        [
            (
                "<tr>"
                f"<td><img src='{row.get('image', '')}' alt='{row.get('symbol', '')} logo' loading='lazy'/></td>"
                f"<td>{row.get('name', '')}</td>"
                f"<td>{(row.get('symbol') or '').upper()}</td>"
                f"<td>{row.get('id', '')}</td>"
                f"<td>{row.get('current_price', '')}</td>"
                f"<td>{row.get('market_cap_rank', '')}</td>"
                "</tr>"
            )
            for row in rows
        ]
    )

    html = f"""<!doctype html>
<html lang=\"en\">
<head>
  <meta charset=\"UTF-8\" />
  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />
  <title>Coin Feed Logo Demo</title>
  <style>
    :root {{
      --bg: #f3f6fb;
      --surface: #ffffff;
      --ink: #102a43;
      --muted: #486581;
      --accent: #0ea5e9;
      --line: #d9e2ec;
    }}
    * {{ box-sizing: border-box; }}
    body {{
      margin: 0;
      font-family: ui-sans-serif, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
      background: linear-gradient(135deg, #f0f7ff 0%, #f6f9ff 60%, #e8f5ff 100%);
      color: var(--ink);
    }}
    .container {{
      max-width: 1080px;
      margin: 2rem auto;
      padding: 0 1rem 2rem;
    }}
    .hero {{
      background: radial-gradient(circle at right top, #67e8f9, #0ea5e9 40%, #0369a1 100%);
      color: #fff;
      border-radius: 18px;
      padding: 1.2rem 1.4rem;
      margin-bottom: 1rem;
      box-shadow: 0 12px 28px rgba(14, 165, 233, 0.25);
    }}
    .hero h1 {{ margin: 0 0 0.4rem; font-size: 1.35rem; }}
    .hero p {{ margin: 0; opacity: 0.95; }}
    .card {{
      background: var(--surface);
      border: 1px solid var(--line);
      border-radius: 14px;
      overflow-x: auto;
      box-shadow: 0 6px 20px rgba(15, 23, 42, 0.08);
    }}
    table {{
      width: 100%;
      border-collapse: collapse;
      min-width: 760px;
    }}
    thead th {{
      text-align: left;
      font-size: 0.84rem;
      color: var(--muted);
      letter-spacing: 0.03em;
      text-transform: uppercase;
      padding: 0.85rem 0.9rem;
      border-bottom: 1px solid var(--line);
      background: #f7fbff;
    }}
    tbody td {{
      padding: 0.85rem 0.9rem;
      border-bottom: 1px solid var(--line);
      font-size: 0.96rem;
    }}
    tbody tr:hover {{ background: #f5fbff; }}
    img {{ width: 28px; height: 28px; border-radius: 50%; object-fit: cover; }}
    .footer {{ color: var(--muted); margin-top: 0.9rem; font-size: 0.9rem; }}
    @media (max-width: 640px) {{
      .hero h1 {{ font-size: 1.1rem; }}
      .hero p {{ font-size: 0.92rem; }}
    }}
  </style>
</head>
<body>
  <div class=\"container\">
    <section class=\"hero\">
      <h1>Crypto Logo Feed Demo</h1>
      <p>Example frontend watchlist using CoinGecko /coins/markets image URLs generated by Python.</p>
    </section>
    <section class=\"card\">
      <table>
        <thead>
          <tr>
            <th>Logo</th>
            <th>Name</th>
            <th>Symbol</th>
            <th>Coin ID</th>
            <th>USD Price</th>
            <th>Rank</th>
          </tr>
        </thead>
        <tbody>
          {row_html}
        </tbody>
      </table>
    </section>
    <p class=\"footer\">Generated by scripts/03_get_bulk_logos_markets.py</p>
  </div>
</body>
</html>
"""
    output_path.write_text(html, encoding="utf-8")
    return output_path
